# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PIL.Image import Image
from PyQt5 import QtCore, QtWidgets

from model import image_editor


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(202, 209)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.label_4.setObjectName("label_4")
        self.moreBrightnessButton = QtWidgets.QPushButton(Dialog)
        self.moreBrightnessButton.setGeometry(QtCore.QRect(140, 20, 21, 21))
        self.moreBrightnessButton.setObjectName("moreBrightnessButton")
        self.lessBrightnessButton = QtWidgets.QPushButton(Dialog)
        self.lessBrightnessButton.setGeometry(QtCore.QRect(170, 20, 21, 21))
        self.lessBrightnessButton.setObjectName("lessBrightnessButton")
        self.lessContrastButton = QtWidgets.QPushButton(Dialog)
        self.lessContrastButton.setGeometry(QtCore.QRect(170, 50, 21, 21))
        self.lessContrastButton.setObjectName("lessContrastButton")
        self.moreContrastButton = QtWidgets.QPushButton(Dialog)
        self.moreContrastButton.setGeometry(QtCore.QRect(140, 50, 21, 21))
        self.moreContrastButton.setObjectName("moreContrastButton")
        self.lessSaturationButton = QtWidgets.QPushButton(Dialog)
        self.lessSaturationButton.setGeometry(QtCore.QRect(170, 80, 21, 21))
        self.lessSaturationButton.setObjectName("lessSaturationButton")
        self.moreSaturationButton = QtWidgets.QPushButton(Dialog)
        self.moreSaturationButton.setGeometry(QtCore.QRect(140, 80, 21, 21))
        self.moreSaturationButton.setObjectName("moreSaturationButton")
        self.moreSharpnessButton = QtWidgets.QPushButton(Dialog)
        self.moreSharpnessButton.setGeometry(QtCore.QRect(140, 110, 21, 21))
        self.moreSharpnessButton.setObjectName("moreSharpnessButton")
        self.lessSharpnessButton = QtWidgets.QPushButton(Dialog)
        self.lessSharpnessButton.setGeometry(QtCore.QRect(170, 110, 21, 21))
        self.lessSharpnessButton.setObjectName("lessSharpnessButton")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_5.setObjectName("label_5")
        self.cropButton = QtWidgets.QPushButton(Dialog)
        self.cropButton.setGeometry(QtCore.QRect(140, 140, 51, 21))
        self.cropButton.setObjectName("cropButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(120, 180, 71, 21))
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(40, 180, 71, 21))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.plus = 1.25
        self.minus = 0.8

        self.set_buttons(Dialog)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit"))
        self.label.setText(_translate("Dialog", "Brightness"))
        self.label_2.setText(_translate("Dialog", "Contrast"))
        self.label_3.setText(_translate("Dialog", "Saturation"))
        self.label_4.setText(_translate("Dialog", "Sharpness"))
        self.moreBrightnessButton.setText(_translate("Dialog", "+"))
        self.lessBrightnessButton.setText(_translate("Dialog", "-"))
        self.lessContrastButton.setText(_translate("Dialog", "-"))
        self.moreContrastButton.setText(_translate("Dialog", "+"))
        self.lessSaturationButton.setText(_translate("Dialog", "-"))
        self.moreSaturationButton.setText(_translate("Dialog", "+"))
        self.moreSharpnessButton.setText(_translate("Dialog", "+"))
        self.lessSharpnessButton.setText(_translate("Dialog", "-"))
        self.label_5.setText(_translate("Dialog", "Crop"))
        self.cropButton.setText(_translate("Dialog", "Crop"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.saveButton.setText(_translate("Dialog", "Save"))

    def set_buttons(self, Dialog):
        self.moreBrightnessButton.clicked.connect(self.on_clicked_more_brightness)
        self.lessBrightnessButton.clicked.connect(self.on_clicked_less_brightness)
        self.moreContrastButton.clicked.connect(self.on_clicked_more_contrast)
        self.lessContrastButton.clicked.connect(self.on_clicked_less_contrast)
        self.moreSaturationButton.clicked.connect(self.on_clicked_more_saturation)
        self.lessSaturationButton.clicked.connect(self.on_clicked_less_saturation)
        self.moreSharpnessButton.clicked.connect(self.on_clicked_more_sharpness)
        self.lessSharpnessButton.clicked.connect(self.on_clicked_less_sharpness)
        self.cropButton.clicked.connect(self.on_click_crop)
        self.saveButton.clicked.connect(self.on_click_save)
        self.cancelButton.clicked.connect(self.on_click_close)
        self.close = Dialog.close

    def setup_editor(self, path, image_view: QtWidgets.QLabel):
        self.editor = image_editor.ImageEditor(path)
        self.image_view = image_view

    def on_clicked_more_brightness(self):
        self.editor.change_brightness(self.plus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_less_brightness(self):
        self.editor.change_brightness(self.minus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_more_contrast(self):
        self.editor.change_contrast(self.plus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_less_contrast(self):
        self.editor.change_contrast(self.minus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_more_saturation(self):
        self.editor.change_saturation(self.plus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_less_saturation(self):
        self.editor.change_saturation(self.minus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_more_sharpness(self):
        self.editor.change_sharpness(self.plus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_clicked_less_sharpness(self):
        self.editor.change_sharpness(self.minus)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_click_crop(self):
        self.editor.crop(0, 0, 200, 200)
        self.image_view.setPixmap(self.editor.img.toqpixmap())

    def on_click_save(self):
        self.editor.save("Test")

    def on_click_close(self):
        self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
