# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadVideoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from model import video_cropper
from model.image_loader import ImageLoader
from view import video_player_dialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 123)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 291, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(310, 10, 71, 23))
        self.browseButton.setObjectName("browseButton")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 361, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(310, 90, 71, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.runButton = QtWidgets.QPushButton(Dialog)
        self.runButton.setGeometry(QtCore.QRect(230, 90, 71, 23))
        self.runButton.setObjectName("runButton")
        self.playButton = QtWidgets.QPushButton(Dialog)
        self.playButton.setGeometry(QtCore.QRect(10, 90, 71, 23))
        self.playButton.setObjectName("playButton")
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setGeometry(QtCore.QRect(10, 70, 371, 16))
        self.statusLabel.setObjectName("StatusLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.files = []

        self.progressBar.setValue(0)
        self.playButton.clicked.connect(self.play)
        self.browseButton.clicked.connect(self.browse)
        self.runButton.clicked.connect(self.run)
        self.cancelButton.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browseButton.setText(_translate("Dialog", "Browse"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.runButton.setText(_translate("Dialog", "Run"))
        self.playButton.setText(_translate("Dialog", "Play"))
        self.statusLabel.setText(_translate("Dialog", "Status:"))

    def browse(self):
        files = QFileDialog.getOpenFileNames(None, None, '', 'Media file(*.mp4 *.wmv *.avi *.3gp *.oog *.mpeg *.mp2 '
                                                             '*.wma *.mp3);;All files(*.*)')
        fname = ""
        for file in files[0]:
            if fname != "":
                fname += "###"
            fname += file
        self.lineEdit.setText(fname)
        self.files = files[0]

    def run(self):
        video_cropper.crop(self.files[0], "1.Lion", [1000, 1005])
        video_cropper.crop(self.files[1], "2.Giraffe", [1020, 1030])
        ImageLoader.__new__(ImageLoader).load()
        self.cancelButton.click()

    def play(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = video_player_dialog.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.ui.setup_media(self.files)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
