# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QMessageBox

from model import inaturalist_api
from model.user_service import UserService


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(172, 147)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 10, 47, 13))
        self.label.setObjectName("label")
        self.usernameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.usernameLineEdit.setGeometry(QtCore.QRect(12, 30, 151, 20))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.passwordLineEdit_2.setGeometry(QtCore.QRect(12, 80, 151, 20))
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(10, 110, 71, 23))
        self.loginButton.setObjectName("loginButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 110, 71, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.loginButton.clicked.connect(self.on_click_login)
        self.cancelButton.clicked.connect(Dialog.close)

        self.passwordLineEdit_2.setEchoMode(QLineEdit.Password)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))

    def on_click_login(self):
        inaturalist_api.login(self.usernameLineEdit.text(), self.passwordLineEdit_2.text())
        if UserService.__new__(UserService).get_access_token() is not None:
            self.cancelButton.click()
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Error: Try logging in with different credentials!")
            msg.setWindowTitle("Error")
            msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
