# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from model import inaturalist_api, user_service
from model.user_service import UserService


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(172, 147)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 10, 47, 13))
        self.label.setObjectName("label")
        self.usernameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.usernameLineEdit.setGeometry(QtCore.QRect(12, 30, 151, 20))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.passwordLineEdit_2.setGeometry(QtCore.QRect(12, 80, 151, 20))
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(10, 110, 71, 23))
        self.loginButton.setObjectName("loginButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 110, 71, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.loginButton.clicked.connect(self.login)
        self.cancelButton.clicked.connect(self.exit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))

    def login(self):
        print("Username: " + self.usernameLineEdit.text() + " | Password: " + self.passwordLineEdit_2.text())
        inaturalist_api.login(self.usernameLineEdit.text(), self.passwordLineEdit_2.text())
        print(UserService.__new__(UserService).get_access_token())

    def exit(self):
        exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
