# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from view import login_dialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(425, 493)
        self.nameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(50, 170, 361, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.descriptionTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.descriptionTextEdit.setGeometry(QtCore.QRect(10, 340, 401, 111))
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(330, 460, 81, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.uploadButton = QtWidgets.QPushButton(Dialog)
        self.uploadButton.setGeometry(QtCore.QRect(240, 460, 81, 23))
        self.uploadButton.setObjectName("uploadButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/black_image.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 290, 47, 21))
        self.label_2.setObjectName("label_2")
        self.longitudeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.longitudeLineEdit.setGeometry(QtCore.QRect(30, 290, 171, 20))
        self.longitudeLineEdit.setObjectName("longitudeLineEdit")
        self.latitudeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.latitudeLineEdit.setGeometry(QtCore.QRect(240, 290, 171, 20))
        self.latitudeLineEdit.setObjectName("latitudeLineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 290, 47, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 47, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 71, 16))
        self.label_5.setObjectName("label_5")
        self.observedOnDateTime = QtWidgets.QDateTimeEdit(Dialog)
        self.observedOnDateTime.setGeometry(QtCore.QRect(290, 200, 121, 22))
        self.observedOnDateTime.setObjectName("observedOnDateTime")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 200, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_7.setObjectName("label_7")
        self.taxonIDLineEdit = QtWidgets.QLineEdit(Dialog)
        self.taxonIDLineEdit.setGeometry(QtCore.QRect(70, 200, 141, 20))
        self.taxonIDLineEdit.setObjectName("taxonIDLineEdit")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 61, 21))
        self.label_8.setObjectName("label_8")
        self.timezoneLineEdit = QtWidgets.QLineEdit(Dialog)
        self.timezoneLineEdit.setGeometry(QtCore.QRect(70, 230, 341, 20))
        self.timezoneLineEdit.setObjectName("timezoneLineEdit")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 47, 21))
        self.label_9.setObjectName("label_9")
        self.placeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.placeLineEdit.setGeometry(QtCore.QRect(70, 260, 341, 20))
        self.placeLineEdit.setObjectName("placeLineEdit")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setEnabled(True)
        self.loginButton.setGeometry(QtCore.QRect(10, 460, 81, 23))
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.loginButton.clicked.connect(self.login)
        self.uploadButton.clicked.connect(self.upload)
        self.cancelButton.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.uploadButton.setText(_translate("Dialog", "Upload"))
        self.label_2.setText(_translate("Dialog", "X:"))
        self.label_3.setText(_translate("Dialog", "Y:"))
        self.label_4.setText(_translate("Dialog", "Name:"))
        self.label_5.setText(_translate("Dialog", "Description:"))
        self.label_6.setText(_translate("Dialog", "Observed on:"))
        self.label_7.setText(_translate("Dialog", "Taxon ID:"))
        self.label_8.setText(_translate("Dialog", "Timezone:"))
        self.label_9.setText(_translate("Dialog", "Place:"))
        self.loginButton.setText(_translate("Dialog", "Login"))

    def login(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = login_dialog.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def upload(self):
        print("Uploaded!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
