# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QInputDialog

from model import popup_window
from model.video_trimmer import trim


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(611, 402)
        self.mediaPlayer = QMediaPlayer(Dialog, QMediaPlayer.VideoSurface)
        videoWidget = QVideoWidget(Dialog)
        videoWidget.setGeometry(QtCore.QRect(10, 10, 591, 321))
        videoWidget.setAutoFillBackground(False)
        videoWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.mediaPlayer.setVideoOutput(videoWidget)
        self.videoSlider = QtWidgets.QSlider(Dialog)
        self.videoSlider.setGeometry(QtCore.QRect(10, 340, 591, 16))
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setObjectName("videoSlider")
        self.playPauseButton = QtWidgets.QPushButton(Dialog)
        self.playPauseButton.setGeometry(QtCore.QRect(280, 360, 51, 31))
        self.playPauseButton.setObjectName("playPauseButton")
        self.backwardButton = QtWidgets.QPushButton(Dialog)
        self.backwardButton.setGeometry(QtCore.QRect(240, 360, 31, 31))
        self.backwardButton.setObjectName("backwardButton")
        self.forwardButton = QtWidgets.QPushButton(Dialog)
        self.forwardButton.setGeometry(QtCore.QRect(340, 360, 31, 31))
        self.forwardButton.setObjectName("forwardButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(530, 370, 71, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(10, 362, 51, 31))
        self.saveButton.setObjectName("saveButton")
        self.trimButton = QtWidgets.QPushButton(Dialog)
        self.trimButton.setGeometry(QtCore.QRect(70, 362, 51, 31))
        self.trimButton.setObjectName("trimButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.isPlaying = False
        self.trimStart = None
        self.trimEnd = None
        self.set_buttons_and_bar(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Player"))
        self.playPauseButton.setText(_translate("Dialog", "Play"))
        self.backwardButton.setText(_translate("Dialog", "|<"))
        self.forwardButton.setText(_translate("Dialog", ">|"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.trimButton.setText(_translate("Dialog", "Trim"))

    def set_buttons_and_bar(self, Dialog):
        self.mediaPlayer.positionChanged.connect(self.video_position_changed)
        self.mediaPlayer.durationChanged.connect(self.video_duration_changed)
        self.videoSlider.sliderMoved.connect(self.set_video_position)
        self.playPauseButton.clicked.connect(self.on_click_play_pause)
        self.backwardButton.clicked.connect(self.on_click_backward)
        self.forwardButton.clicked.connect(self.on_click_forward)
        self.saveButton.clicked.connect(self.on_click_save)
        self.trimButton.clicked.connect(self.on_click_trim)
        self.cancelButton.clicked.connect(Dialog.close)

    def setup_media(self, vids):
        self.videos = vids
        self.video_pointer = 0
        self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile(self.videos[self.video_pointer])))

    def on_click_play_pause(self):
        if self.isPlaying is False:
            self.playPauseButton.setText("Pause")
            self.isPlaying = True
            self.mediaPlayer.play()
        else:
            self.playPauseButton.setText("Play")
            self.isPlaying = False
            self.mediaPlayer.pause()

    def on_click_backward(self):
        if self.video_pointer - 1 > -1:
            self.video_pointer -= 1
            self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile(self.videos[self.video_pointer])))
            self.playPauseButton.setText("Play")
            self.isPlaying = False
            self.mediaPlayer.pause()

    def on_click_forward(self):
        if self.video_pointer + 1 < len(self.videos):
            self.video_pointer += 1
            self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile(self.videos[self.video_pointer])))
            self.playPauseButton.setText("Play")
            self.isPlaying = False
            self.mediaPlayer.pause()

    def on_click_trim(self):
        position = int(self.mediaPlayer.position())
        if self.trimStart is None:
            self.trimStart = (position - position % 1000) / 1000
        elif self.trimEnd is None:
            self.trimEnd = (position - position % 1000) / 1000

    def on_click_save(self):
        if self.trimEnd and self.trimStart:
            title = str(QInputDialog.getText(None, "Input", "What is the title you want?"))
            if title is not None:
                trim(self.videos[self.video_pointer], self.trimStart, self.trimEnd, title)
        else:
            popup_window.warning("You need to select a start and end to trim!")

    def video_position_changed(self, position):
        self.videoSlider.setValue(position)

    def video_duration_changed(self, duration):
        self.videoSlider.setRange(0, duration)

    def set_video_position(self, position):
        self.mediaPlayer.setPosition(position)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
